services:
  - type: web
    name: smart-resume-screening
    env: python
<<<<<<< HEAD
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        value: "postgresql://sams_db_gynz_user:Zf0Y2Nh2uWQZQwP5eLSUuaBDxWSAiwHL@dpg-d7iik7t8nd3s738hufgg-a/sams_db_gynz"
    disk:
      mountPath: /app/media
      sizeGB: 1
=======
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_HR_SECRET_CODE
        value: "change_this_secret"
      - key: DATABASE_URL
        fromDatabase:
          name: smart-resume-screening-db
          property: connectionString
  - type: pserv
    name: smart-resume-screening-db
    env: postgres
    plan: free
    # database is created automatically
>>>>>>> 7216b07 (Ready for Render deployment with PostgreSQL)
