# Generated by Django 6.0.3 on 2026-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_assigned_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='selection_stage',
            field=models.CharField(choices=[('NONE', 'Not Selected'), ('ROUND2', 'Round 2 Selected'), ('ROUND3', 'Round 3 Selected'), ('DIRECT', 'Direct Selection')], default='NONE', max_length=20),
        ),
    ]
