# Generated by Django 6.0.3 on 2026-04-08 11:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_is_selected_application_offer_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_offer_letter',
            field=models.FileField(blank=True, null=True, upload_to=core.models.offer_upload_path),
        ),
    ]
