"""
Bundle all project Python source into CODEBOOK_FULL.md, CODEBOOK_FULL.pdf, CODEBOOK_FULL.docx.

Run from project root: python docs/build_full_codebook.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = Path(__file__).resolve().parent
SKIP_PARTS = frozenset({".venv", "venv", "__pycache__", ".git", "site-packages", "node_modules"})
MD_OUT = DOCS / "CODEBOOK_FULL.md"
PDF_OUT = DOCS / "CODEBOOK_FULL.pdf"
DOCX_OUT = DOCS / "CODEBOOK_FULL.docx"


def skip_path(p: Path) -> bool:
    return any(part in SKIP_PARTS for part in p.parts)


def collect_py_files() -> list[Path]:
    files = [p for p in ROOT.rglob("*.py") if not skip_path(p)]
    return sorted(files, key=lambda x: (len(x.parts), str(x).lower()))


def build_markdown(files: list[Path]) -> str:
    lines = [
        "# Smart Resume Screening — Full Python Source Codebook",
        "",
        "Auto-generated bundle of all `.py` files (excluding `.venv`, `__pycache__`, etc.).",
        "",
        "---",
        "",
    ]
    for fp in files:
        rel = fp.relative_to(ROOT)
        try:
            text = fp.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            text = f"<could not read file: {e}>"
        lines.append(f"## `{rel.as_posix()}`")
        lines.append("")
        lines.append("```python")
        lines.append(text.rstrip())
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def build_pdf(files: list[Path], out_path: Path) -> None:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer
    from xml.sax.saxutils import escape

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "T", parent=styles["Heading1"], fontSize=12, spaceAfter=10, spaceBefore=0
    )
    path_style = ParagraphStyle(
        "P", parent=styles["Heading2"], fontSize=9, spaceAfter=6, spaceBefore=14
    )
    code_style = ParagraphStyle(
        "C",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=6,
        leading=7,
    )

    story = []
    story.append(Paragraph(escape("Smart Resume Screening — Full Python Source (PDF)"), title_style))
    story.append(
        Paragraph(
            escape("One section per file. Generated by docs/build_full_codebook.py"),
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 0.4 * cm))

    for i, fp in enumerate(files):
        if i:
            story.append(PageBreak())
        rel = fp.relative_to(ROOT)
        story.append(Paragraph(escape(rel.as_posix()), path_style))
        try:
            text = fp.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            text = f"<could not read file: {e}>"
        for line in text.splitlines():
            story.append(Paragraph(escape(line[:3000]), code_style))

    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=1.0 * cm,
        rightMargin=1.0 * cm,
        topMargin=1.0 * cm,
        bottomMargin=1.0 * cm,
    )
    doc.build(story)


def build_docx(files: list[Path], out_path: Path) -> None:
    from docx import Document
    from docx.enum.text import WD_LINE_SPACING
    from docx.shared import Pt

    doc = Document()
    doc.add_heading("Smart Resume Screening — Full Python Source", level=0)
    doc.add_paragraph(
        "Auto-generated. Excludes .venv and __pycache__. Each heading is one file; body is full source."
    )

    for fp in files:
        rel = fp.relative_to(ROOT)
        doc.add_heading(str(rel).replace("\\", "/"), level=1)
        try:
            text = fp.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            text = f"<read error: {e}>"
        p = doc.add_paragraph(text)
        for run in p.runs:
            run.font.name = "Consolas"
            run.font.size = Pt(6.5)
        p.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        p.paragraph_format.space_after = Pt(4)

    doc.save(out_path)


def main() -> int:
    files = collect_py_files()
    md = build_markdown(files)
    MD_OUT.write_text(md, encoding="utf-8")
    print(f"Wrote {MD_OUT} ({len(files)} files)")

    build_pdf(files, PDF_OUT)
    print(f"Wrote {PDF_OUT}")

    build_docx(files, DOCX_OUT)
    print(f"Wrote {DOCX_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
